export { startTests } from '@vitest/runner';
export { s as setupCommonEnv } from './chunk-runtime-setup.28d2d580.js';
export { s as setupSnapshotEnvironment } from './chunk-snapshot-env.6457638e.js';
import '@vitest/utils';
import './chunk-integrations-run-once.38756e30.js';
import './chunk-utils-global.442d1d33.js';
import 'pathe';
import './chunk-utils-env.860d90c2.js';
import 'std-env';
import '@vitest/runner/utils';
